version: '3'

services:
  app:
    container_name: docker-testnet
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '8888:27017'
